### ISSUE TITLE
Parsing of <notes> Tag

### ISSUE THREAD

**Issue by MokshaPadsalgi** [elifesciences/elife-tools#351]
# Description

# Tasks

- [ ] Update parseJATS.py for populating any missing elements related to <notes> tag like content-type="reviewer-name" etc
- [ ] Update parseJATS.py for parsing the notes tag
- [ ] Notes tag might contain various elements like <list-item>, <named-content content-type="reviewer-name">, <fn> etc. Verifying that all the tags are being handled properly
- [ ] Adding xmls containing various examples for the same

# Definition of Done

- [ ] <notes> tag is getting parsed correctly by adding new content type and all the elements present within the <notes> tag are populated within the content.
- [ ] Various unit tests covering different scenarios of representing notes tag 
- [ ] Solution deployed into a production environment and accessible to users.
- [ ] Solution reviewed and approved by all stakeholders.

**Comment by gnott** [comment]
Thanks for raising the issue @MokshaPadsalgi. If you choose to start on it, please let me know how I could help you. Please keep in mind I am just starting to do some code linting and I'm planning to improve the test scenarios, so many files may get moved around in the next week or two, then it will be more stable again to accept pull requests.
